### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Reynbow** [NG0N/BloodwebAutoBuy#1]
Having issues running app.
Resolution is 3440x1440.
Output is: https://i.imgur.com/9RwfUWB.jpeg
OS is Windows 11

**Comment by kruemmelbande** [comment]
From looking into the code, it looks like it didnt find any buyable nodes. Do you have dbd open and the bloodweb shown?

**Comment by Reynbow** [comment]
Interesting. I do have it open. I tried it again and this time instead of showing an error it just blinks the cursor in the top left corner of the screen, about 40 pixels in on the x and y

No filters on
No f.lux running
Just base game

EDIT: Just realised, maybe it's because I have an HDR monitor?
I remembered that when I take screenshots are sometimes very blown out depending on what's taking the screenshot

EDIT2: turned off HDR and same thing
still borked

**Comment by Reynbow** [comment]
Just downloaded the latest update you posted. It's now working
